import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const repoRoot = path.resolve(__dirname, '..');
const artifactPath = path.join(repoRoot, 'contracts/artifacts/contracts/HTLCEscrow.sol/HTLCEscrow.json');
const outputPath = path.join(repoRoot, 'packages/sdk/src/ethereum/abi.ts');

function main() {
  console.log('Generating SDK ABI from contract artifacts...');

  if (!fs.existsSync(artifactPath)) {
    console.error(`❌ Error: Contract artifact not found at ${artifactPath}`);
    console.error('Please run contract compilation first: pnpm --filter @wafflefinance/contracts compile');
    process.exit(1);
  }

  try {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
    const abi = artifact.abi;

    if (!abi) {
      console.error('❌ Error: No ABI field found in the contract artifact JSON.');
      process.exit(1);
    }

    const content = `// This file is auto-generated from the compiled HTLCEscrow contract artifact.
// Do not edit this file manually.

export const HTLC_ESCROW_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;

    // Ensure parent directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content, 'utf8');
    console.log(`✅ Successfully updated SDK ABI at ${outputPath}`);
  } catch (error) {
    console.error(`❌ Failed to update SDK ABI: ${error.message}`);
    process.exit(1);
  }
}

main();
